# Generated by Django 5.1.2 on 2024-10-26 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('timeToTake', models.DurationField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='venues.venue')),
            ],
        ),
    ]
