# Generated by Django 5.1.2 on 2024-10-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='venue',
            new_name='venue_id',
        ),
    ]
