# Generated by Django 5.1.2 on 2024-10-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_venue_product_venue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timeToTake',
        ),
        migrations.AddField(
            model_name='product',
            name='minutesToTake',
            field=models.IntegerField(default=0.00018298931342409602),
            preserve_default=False,
        ),
    ]
