# Generated by Django 5.1.2 on 2024-10-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=0.00015937778911130943, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.TextField(default=0.00015937778911130943),
            preserve_default=False,
        ),
    ]
